### PR TITLE
fix: issue causing `scripts/` to be importable outside of this project [SBK-151]

### PR DESCRIPTION
**Pull request by antazoey**
fixes: #14 
Fixes: SBK-151

To test, run:

```python
python -c "import scripts; print(scripts.__path__)"
```
from your home directory or somewhere else that is not this repo

I tried everything I could think of for like an hour to avoid having to make a separate `src/` dir.
I tried using `package`, `include`, and `exclude` to make it so it would not include scripts or tests. It never happened! I don't know why.

But the second i made it look for packages only in the `src` directory, things were fine.

### CODE REVIEW

**Comment by antazoey** [comment]
@fubuloubu any other ideas or do we just count this as a behavior of poetry? They don't see it as an issue it seems even though the equivalent fix on setup.py projects works. We either have to change the project structure or not use Poetry or accept that `tests` and `scripts` will always be added to `sys.path`

**Comment by fubuloubu** [comment]
> @fubuloubu any other ideas or do we just count this as a behavior of poetry? They don't see it as an issue it seems even though the equivalent fix on setup.py projects works. We either have to change the project structure or not use Poetry or accept that `tests` and `scripts` will always be added to `sys.path`

I think it's okay (and even somewhat desirable in the case of `scripts/`) since those are unlikely to be real packages:
- https://pypi.org/project/tests/
- https://pypi.org/project/scripts/

**Comment by antazoey** [comment]
> I think it's okay (and even somewhat desirable in the case of `scripts/`) since those are unlikely to be real packages:

Because of the issues it had causes in Ape and the increase of complexity that followed, I am inclined to dislike this behavior.
Nonetheless, we "fixed" it in Ape so it is okay.

**Comment by antazoey** [comment]
closing but be warned.

**Pull request closed without merging**
