### PR TITLE
feat: support for ape 0.7, silverback 0.3, and pydantic 2

### PR DESCRIPTION
**Pull request by mikeshultz**
Upgrades Ape, Silverback, Pydantic.  Fixes some other type issues.

### CODE REVIEW

**Comment by mikeshultz** [comment]
Merging this might have unknown impact.  Everything is pointed at this repo's main branch and we haven't done a release since September.  So anything based on ape<0.7 may break.

Could drag our feet and point things at this branch?  Though once the branch gets deleted then that all gets broken too.  Suggestions?

**Comment by mikeshultz** [comment]
Yeah, I think this branch needs to live for a little while.  So either we don't merge this PR or don't delete the branch if we do (not sure if auto in this repo).

**Review by fubuloubu — APPROVED** [review]

**Comment by antazoey** [comment]
Can we merge this?
I can then update to 0.8.
I need to test some Ape features on this project...

**Comment by fubuloubu** [comment]
> Can we merge this?
> I can then update to 0.8.
> I need to test some Ape features on this project...

Its old enough you are probably better off doing the upgrade in this PR to see if the updates still work

And yes, i nees this soon too haha

**Comment by antazoey** [comment]
actually https://github.com/ApeWorX/ApePay/pull/97

**Comment by fubuloubu** [comment]
closed in favor of #97

**Pull request closed without merging**
